$UWPApps = @(
"Microsoft.VCLibs.140.00"
"Microsoft.UI.Xaml.2.0"
"Microsoft.Advertising.Xaml"
"microsoft.windowscommunicationsapps"
"Microsoft.WindowsStore"
"Microsoft.DesktopAppInstaller"
"Microsoft.XboxIdentityProvider"
"Microsoft.WindowsAlarms"
"Microsoft.SkypeApp"
"Microsoft.ZuneVideo"
"Microsoft.ZuneMusic"
"Microsoft.YourPhone"
"Microsoft.XboxSpeechToTextOverlay"
"Microsoft.XboxGameOverlay"
"Microsoft.XboxApp"
"Microsoft.Xbox.TCUI"
"Microsoft.WindowsSoundRecorder"
"Microsoft.WindowsMaps"
"Microsoft.WindowsFeedbackHub"
"Microsoft.WebpImageExtension"
"Microsoft.WebMediaExtensions"
"Microsoft.Wallet"
"Microsoft.VP9VideoExtensions"
"Microsoft.StorePurchaseApp"
"Microsoft.ScreenSketch"
"Microsoft.People"
"Microsoft.Office.OneNote"
"Microsoft.MixedReality.Portal"
"Microsoft.Services.Store.Engagement"
"Microsoft.Services.Store.Engagement"
"Microsoft.MicrosoftSolitaireCollection"
"Microsoft.MicrosoftOfficeHub"
"Microsoft.Microsoft3DViewer"
"Microsoft.HEIFImageExtension"
"Microsoft.Getstarted"
"Microsoft.GetHelp"
"Microsoft.BingWeather"
"Microsoft.MicrosoftEdge.Stable"
)
foreach ($UWPApp in $UWPApps) {
Get-AppxPackage -Name $UWPApp -AllUsers | Remove-AppxPackage
Get-AppXProvisionedPackage -Online | Where-Object DisplayName -eq $UWPApp | Remove-AppxProvisionedPackage -Online
}
